import { LayoutTemplate, UserPen, QrCode } from "lucide-react"

import {
  TemplateComponent,
  VcardCreateForm,
  VcardQrCodeDesign,
} from "@/components/dynamic"

export const stepperVcardData = [
  {
    id: 43453453245,
    Icon: LayoutTemplate,
    label: "Choose Template",
    index: 0,
    Component: TemplateComponent,
    fields: ["templateId"],
  },
  {
    id: 4373463456,
    Icon: UserPen,
    label: "Enter Information",
    index: 1,
    Component: VcardCreateForm,
    fields: [
      "profileImage",
      "images",
      "userName",
      "firstName",
      "lastName",
      "middleName",
      "prefix",
      "suffix",
      "mobileNumber",
      "workNumber",
      "homeNumber",
      "whatsappNumber",
      "faxNumber",
      "personalEmail",
      "workEmail",
      "homeStreet",
      "homeCity",
      "homeState",
      "homeZip",
      "homeCountry",
      "workStreet",
      "workCity",
      "workState",
      "workZip",
      "workCountry",
      "website",
      "company",
      "jobTitle",
      "department",
      "linkedin",
      "twitter",
      "instagram",
      "facebook",
      "note",
    ],
  },
  {
    id: 33456346346,
    Icon: QrCode,
    label: "Create QR Code",
    index: 2,
    Component: VcardQrCodeDesign,
    fields: [
      "title",
      "style.color",
      "style.bottomInput",
      "style.topInput",
      "style.shape",
      "style.hasFramee",
      "style.image",
    ],
  },
]
